# Linear Algebra

You need to know a little bit of linear algebra because a number of the machine learning techniques are expressed more compactly if you use the appropriate notation.

We shall see some applications later, but remember that it is all about not having to write as much.


# Vectors
For example, if you want to have a list of values, we can use a vector $v=[0, 1, 3, 4]$.

In general, we would write $x = [x_1, x_2, ..., x_n]$ and can refer to a particular value with the subscript notation $x_i$ is the i'th value in the vector.

# Matrices
A 2D matrix is a rectangular arrangement of values.  There are a number of ways that matrices can be used, but the basics involve combining two matrices or a matrix with a vector.

Here is an example of a 4 by 3 matrix $\mathbf{M} = \left[\begin{array}{ccc}1&2&3\\
4&5&6\\
7&8&9\\
10&11&12
\end{array}
\right]$

We can refer to individual values in the matrix via a subscript like so:

$\mathbf{A} = \left[\begin{array}{cccc}
a_{1,1}&a_{1,2}&...&a_{1,n}\\
a_{2,1}&a_{2,2}&...&a_{2,n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m,1}&a_{m,2}&...&a_{m,n}
\end{array}
\right]$

where A is m rows by n columns. We can use a double subscript to refer to values in the array $a_{i,j}$.


## How do I use numpy?
You need to import the package.  In the olden days, the package name was np, so we are going to use that name when we work with numpy

# Combining a Matrix and a Vector
One standard operation is to multiply a matrix with a vector and produce as a result a new vector. This kind of operation is often linked with transformation of data.  Matrices used in this fashion are called _Transformation Matrices_.  We will define how to do the operation here and look at the corresponding python code and then show that it can be done quicker with numpy.

$\mathbf{A}x = \left[\begin{array}{cccc}
a_{1,1}&a_{1,2}&...&a_{1,n}\\
a_{2,1}&a_{2,2}&...&a_{2,n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m,1}&a_{m,2}&...&a_{m,n}
\end{array} 
\right]
\left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\vdots\\
x_n
\end{array} 
\right]
= [
$

In [1]:
import numpy as np

## Basic numpy structures
We will just work with vectors and matrices... or in numpy speak: arrays.  To create a numpy array we need to give it a list that contains the values in our array

## Vector
A vector is just a one-dimensional array. So to create it we just pass in a list with the values. Here are some examples...  S

In [3]:
#This vector has 3 values in it
vector1 = np.array([1, 2, 3])
print(vector1)

#This vector has 4 values in it
vector2 = np.array([1.5, 2.7, 8.9, 24])
print(vector2)

[1 2 3]
[ 1.5  2.7  8.9 24. ]


### Basic operations on Vectors

### Vector addition
If you have two vectors of the same size, you can add them together.  The resulting vector just adds the corresponding values together

In [12]:
#These vectors have 3 values in them
vectorA = np.array([1, 2, 3])
vectorB = np.array([0, 5, 10])

print(vectorA)
print(vectorB)
# Put the sum in vectorC
# Result is [1+0, 2+5, 3+10]
vectorC = vectorA + vectorB
print(vectorC)



[1 2 3]
[ 0  5 10]
[ 1  7 13]


### Vector products
When working with vectors we have a couple ways that we can do a
multiplication like operation.  The inner or dot product takes the
corresponding values in the two vectors and multiplies them together.
It then takes each of those products and adds them together resulting
in a single value.   The outer product is more complicated and used
less often. (It results in a 2D array.)

In [13]:
#The dot product of my two vectors
#Result is 1*0 + 2*5 + 3*10
product = vectorA @ vectorB
print(vectorA)
print(vectorB)
print(product)

# or we can do it as
product = vectorA.dot(vectorB)
print(product)

[1 2 3]
[ 0  5 10]
40
40


## Matrices
A matrix is a multidimensional array.  For our purposes, we will almost always work with 2D arrays, or sometimes 3D arrays.  To create an array we need to create a list of lists.  See the following example.

In [16]:
## The following is a 3 by 3 matrix
matrixA = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(matrixA)

## The following is a 2 by 4 matrix   (2 rows and 4 columns)
matrixB = np.array([[1, 2, 3, 4], 
                    [4, 5, 6, 8]])
print(matrixB)

# We can find the size of the array by asking for its shape
print(matrixA.shape)
print(matrixB.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4]
 [4 5 6 8]]
(3, 3)
(2, 4)


### Take me to your leader (the official docs)
http://www.numpy.org